export const fontsizeOption: Array<string> = ['sm', 'base', 'lg', 'xl', '2xl']
export const widthOption: Array<string> = ['1/6', '1/5', '1/3', '1/2', 'full', 'auto']
export const resizeOption: Array<string> = ['both', 'vertical', 'horizontal', 'none']
export const sizeOption: Array<string> = ['small', 'medium', 'large']
export const colorOption: Array<string> = ['primary', 'secondary', 'success', 'error', 'info', 'warning']
